version:  '3.4'
services: 
  app: 
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /app
    volumes:
      - ./node_backend/settings.js:/app/settings.js:cached
    working_dir: /app
    ports: 
      - '${APP_PORT:-1337}:1337'
    # command:  
    #   bash -c "npm run server & gunicorn --bind 0.0.0.0:1337 app:app"